### ISSUE TITLE
while running i got this error how i solve plzzz

### ISSUE THREAD

**Issue by BIS5162443** [eclipse/ponte#40]
module.js:328
    throw err;
    ^

Error: Cannot find module 'mosca'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/kop/Desktop/project/ponte-master/lib/servers.js:17:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by chombium** [comment]
Hi,

have you maybe forgot to run ```npm install``` before starting Ponte?
